export const roleCreateMock = {
    "role": {
        "fk_property": 1,
        "fk_entity": 152831,
        "temporal_entity": {
            "fk_class": 3
        }
    },
    "isOutgoing": false,
    "isCircular": false,
    "targetDfhClass": {
        "dfh_pk_class": 3,
        "dfh_identifier_in_namespace": "F52",
        "dfh_standard_label": "Name Use Activity",
        "pk_entity": 728,
        "entity_version": 1,
        "notes": null,
        "tmsp_creation": "2018-06-04T10:18:05.637Z",
        "tmsp_last_modification": "2018-06-04T10:18:05.637Z",
        "sys_period": "[\"2018-06-04 10:18:05.637764+00\",)",
        "text_properties": []
    },
    "toggle": "expanded",
    "_teEnt": {
        "selectPropState": "init",
        "toggle": "collapsed",
        "teEnt": {
            "fk_class": 3
        },
        "fkClass": 3,
        "dfhClass": {
            "dfh_pk_class": 3,
            "dfh_identifier_in_namespace": "F52",
            "dfh_standard_label": "Name Use Activity",
            "pk_entity": 728,
            "entity_version": 1,
            "notes": null,
            "tmsp_creation": "2018-06-04T10:18:05.637Z",
            "tmsp_last_modification": "2018-06-04T10:18:05.637Z",
            "sys_period": "[\"2018-06-04 10:18:05.637764+00\",)",
            "text_properties": []
        },
        "ingoingRoleSets": [],
        "outgoingRoleSets": [
            {
                "isOutgoing": true,
                "property": {
                    "dfh_pk_property": 1,
                    "dfh_identifier_in_namespace": "R63",
                    "dfh_has_domain": 3,
                    "dfh_has_range": 1,
                    "dfh_creation_time": null,
                    "dfh_modification_time": null,
                    "dfh_standard_label": "Named",
                    "dfh_domain_instances_min_quantifier": 0,
                    "dfh_domain_instances_max_quantifier": -1,
                    "dfh_range_instances_min_quantifier": 0,
                    "dfh_range_instances_max_quantifier": -1,
                    "pk_entity": 736,
                    "entity_version": 1,
                    "notes": null,
                    "tmsp_creation": "2018-06-04T10:18:17.302Z",
                    "tmsp_last_modification": "2018-06-04T10:18:17.302Z",
                    "sys_period": "[\"2018-06-04 10:18:17.302383+00\",)",
                    "labels": [
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Entity with this Name",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 1,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 751,
                            "entity_version": 1,
                            "notes": "label.sg",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Entities with this Name",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 1,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 752,
                            "entity_version": 1,
                            "notes": "label.pl",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Name",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 1,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 753,
                            "entity_version": 1,
                            "notes": "label_inversed.sg",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Names",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 1,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 754,
                            "entity_version": 1,
                            "notes": "label_inversed.pl",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        }
                    ],
                    "text_properties": []
                },
                "targetClassPk": 1,
                "label": {
                    "sg": "Entity with this Name",
                    "pl": "Entities with this Name",
                    "default": "Entities with this Name"
                }
            },
            {
                "isOutgoing": true,
                "property": {
                    "dfh_pk_property": 2,
                    "dfh_identifier_in_namespace": "R64",
                    "dfh_has_domain": 3,
                    "dfh_has_range": 2,
                    "dfh_creation_time": null,
                    "dfh_modification_time": null,
                    "dfh_standard_label": "Used Name",
                    "dfh_domain_instances_min_quantifier": 0,
                    "dfh_domain_instances_max_quantifier": -1,
                    "dfh_range_instances_min_quantifier": 1,
                    "dfh_range_instances_max_quantifier": 1,
                    "pk_entity": 737,
                    "entity_version": 1,
                    "notes": null,
                    "tmsp_creation": "2018-06-04T10:18:17.302Z",
                    "tmsp_last_modification": "2018-06-04T10:18:17.302Z",
                    "sys_period": "[\"2018-06-04 10:18:17.302383+00\",)",
                    "labels": [
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Detailed Name",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 2,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 755,
                            "entity_version": 1,
                            "notes": "label.sg",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Detailed Names",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 2,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 756,
                            "entity_version": 1,
                            "notes": "label.pl",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Names with this details",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 2,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 757,
                            "entity_version": 1,
                            "notes": "label_inversed.sg",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Name with this details",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 2,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 758,
                            "entity_version": 1,
                            "notes": "label_inversed.pl",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        }
                    ],
                    "text_properties": []
                },
                "targetClassPk": 2,
                "label": {
                    "sg": "Detailed Name",
                    "pl": "Detailed Names",
                    "default": "Detailed Name"
                }
            },
            {
                "isOutgoing": true,
                "property": {
                    "dfh_pk_property": 3,
                    "dfh_identifier_in_namespace": "R61",
                    "dfh_has_domain": 3,
                    "dfh_has_range": 4,
                    "dfh_creation_time": null,
                    "dfh_modification_time": null,
                    "dfh_standard_label": "Occured in kind of context",
                    "dfh_domain_instances_min_quantifier": 0,
                    "dfh_domain_instances_max_quantifier": -1,
                    "dfh_range_instances_min_quantifier": 1,
                    "dfh_range_instances_max_quantifier": 1,
                    "pk_entity": 738,
                    "entity_version": 1,
                    "notes": null,
                    "tmsp_creation": "2018-06-04T10:18:17.302Z",
                    "tmsp_last_modification": "2018-06-04T10:18:17.302Z",
                    "sys_period": "[\"2018-06-04 10:18:17.302383+00\",)",
                    "labels": [
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Language",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 3,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 759,
                            "entity_version": 1,
                            "notes": "label.sg",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Languages",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 3,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 760,
                            "entity_version": 1,
                            "notes": "label.pl",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Name with this language",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 3,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 761,
                            "entity_version": 1,
                            "notes": "label_inversed.sg",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        },
                        {
                            "dfh_pk_label": null,
                            "dfh_label": "Names with this language",
                            "dfh_language_iso_code": null,
                            "dfh_is_standard_label_for_language": null,
                            "dfh_fk_property": 3,
                            "dfh_fk_namespace": null,
                            "dfh_fk_class": null,
                            "dfh_fk_project": null,
                            "dfh_fk_class_type": null,
                            "dfh_fk_property_type": null,
                            "dfh_fk_profile": null,
                            "dfh_creation_time": null,
                            "dfh_modification_time": null,
                            "pk_entity": 762,
                            "entity_version": 1,
                            "notes": "label_inversed.pl",
                            "tmsp_creation": "2018-06-04T10:18:20.036Z",
                            "tmsp_last_modification": "2018-06-04T10:18:20.036Z",
                            "sys_period": "[\"2018-06-04 10:18:20.036434+00\",)"
                        }
                    ],
                    "text_properties": []
                },
                "targetClassPk": 4,
                "label": {
                    "sg": "Language",
                    "pl": "Languages",
                    "default": "Language"
                }
            },
            {
                "isOutgoing": true,
                "property": {
                    "dfh_pk_property": 7,
                    "dfh_identifier_in_namespace": "R63",
                    "dfh_has_domain": 3,
                    "dfh_has_range": 363,
                    "dfh_creation_time": null,
                    "dfh_modification_time": null,
                    "dfh_standard_label": "Named",
                    "dfh_domain_instances_min_quantifier": 0,
                    "dfh_domain_instances_max_quantifier": -1,
                    "dfh_range_instances_min_quantifier": 0,
                    "dfh_range_instances_max_quantifier": -1,
                    "pk_entity": 742,
                    "entity_version": 1,
                    "notes": null,
                    "tmsp_creation": "2018-06-04T10:18:17.302Z",
                    "tmsp_last_modification": "2018-06-04T10:18:17.302Z",
                    "sys_period": "[\"2018-06-04 10:18:17.302383+00\",)",
                    "labels": [],
                    "text_properties": []
                },
                "targetClassPk": 363,
                "label": {
                    "sg": "n.N.",
                    "pl": "n.N.",
                    "default": "n.N."
                }
            }
        ],
        "label": null
    }
}