-- 1
-- CREATE OR REPLACE VIEW warehouse.v_fk_entity_label AS
--  WITH entities AS (
--          SELECT v_entities.pk_entity,
--             v_entities.fk_project,
--             v_entities.project,
--             v_entities.fk_class,
--             v_entities.table_name,
--             v_entities.entity_type
--            FROM warehouse.v_entities
--         )
--  SELECT entities.pk_entity,
--     entities.fk_project,
--     entities.project,
--     entities.fk_class,
--     entities.table_name,
--     entities.entity_type,
--     a.fk_entity_label
--    FROM entities
--      LEFT JOIN ( SELECT r.fk_entity AS pk_entity,
--             r.fk_temporal_entity AS fk_entity_label,
--             r.fk_project,
--             row_number() OVER (PARTITION BY r.fk_entity, (COALESCE(r.fk_project, 0)) ORDER BY r.rank_for_pe_it) AS rank
--            FROM warehouse.v_roles_per_project_and_repo r
--              JOIN projects.class_field_config ucc ON ucc.fk_property = r.fk_property AND ucc.ord_num = 0 AND ucc.property_is_outgoing = false AND ucc.fk_app_context = 45
--              JOIN information.entity e ON r.fk_temporal_entity = e.pk_entity AND e.table_name::text = 'temporal_entity'::text
--         UNION
--          SELECT r.fk_temporal_entity AS pk_entity,
--             r.fk_entity AS fk_entity_label,
--             r.fk_project,
--             row_number() OVER (PARTITION BY r.fk_temporal_entity, (COALESCE(r.fk_project, 0)) ORDER BY r.rank_for_te_ent) AS rank
--            FROM warehouse.v_roles_per_project_and_repo r
--              JOIN projects.class_field_config ucc ON ucc.fk_property = r.fk_property AND ucc.ord_num = 0 AND ucc.property_is_outgoing = true AND ucc.fk_app_context = 45
--              JOIN information.entity e ON r.fk_entity = e.pk_entity AND e.table_name::text = 'persistent_item'::text) a ON a.pk_entity = entities.pk_entity AND NOT a.fk_project IS DISTINCT FROM entities.fk_project
--   WHERE a.rank = 1;

-- 1
DROP VIEW warehouse.v_roles_per_project_and_repo_no_rank;

-- 0
DROP VIEW information.v_role_tmp;
