export * from './account.service';
import { AccountService } from './account.service';
export * from './accountData.service';
import { AccountDataService } from './accountData.service';
export * from './analysis.service';
import { AnalysisService } from './analysis.service';
export * from './backoffice.service';
import { BackofficeService } from './backoffice.service';
export * from './communityVisibility.service';
import { CommunityVisibilityService } from './communityVisibility.service';
export * from './contentTree.service';
import { ContentTreeService } from './contentTree.service';
export * from './datChunkController.service';
import { DatChunkControllerService } from './datChunkController.service';
export * from './dataModel.service';
import { DataModelService } from './dataModel.service';
export * from './factoidController.service';
import { FactoidControllerService } from './factoidController.service';
export * from './importTableController.service';
import { ImportTableControllerService } from './importTableController.service';
export * from './languages.service';
import { LanguagesService } from './languages.service';
export * from './ontoMeController.service';
import { OntoMeControllerService } from './ontoMeController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './projectConfiguration.service';
import { ProjectConfigurationService } from './projectConfiguration.service';
export * from './projectData.service';
import { ProjectDataService } from './projectData.service';
export * from './ramList.service';
import { RamListService } from './ramList.service';
export * from './subfieldPageController.service';
import { SubfieldPageControllerService } from './subfieldPageController.service';
export * from './systemConfiguration.service';
import { SystemConfigurationService } from './systemConfiguration.service';
export * from './systemTypes.service';
import { SystemTypesService } from './systemTypes.service';
export * from './table.service';
import { TableService } from './table.service';
export * from './warEntityPreviewController.service';
import { WarEntityPreviewControllerService } from './warEntityPreviewController.service';
export const APIS = [AccountService, AccountDataService, AnalysisService, BackofficeService, CommunityVisibilityService, ContentTreeService, DatChunkControllerService, DataModelService, FactoidControllerService, ImportTableControllerService, LanguagesService, OntoMeControllerService, PingControllerService, ProjectConfigurationService, ProjectDataService, RamListService, SubfieldPageControllerService, SystemConfigurationService, SystemTypesService, TableService, WarEntityPreviewControllerService];
