import { PropertyFieldList, FieldList, EntityPreviewList, PeItDetailList } from 'app/core/state/models';
import { ComClassFieldInterface, ComUiContextInterface, ComProjectInterface, InfChunk, InfPersistentItem, InfTemporalEntity, DfhProperty } from 'app/core/sdk';
import { ClassSettingsI } from 'app/modules/projects/containers/class-settings/api/class-settings.models';
import { EntityDetail } from 'app/modules/information/containers/entity-detail/api/entity-detail.models';
import { SourceDetail } from 'app/modules/sources/containers/source-detail/api/source-detail.models';
import { ClassAndTypePk } from 'app/modules/information/containers/class-and-type-selector/api/class-and-type-selector.models';
import { SectionDetail } from 'app/modules/sources/containers/section-detail/api/section-detail.models';
import { Observable } from 'rxjs';
import { QueryDetail } from 'app/modules/queries/containers/query-detail/api/query-detail.models';

export interface ChunkList { [pk_entity: number]: InfChunk };
export interface PeItList { [pk_entity: number]: InfPersistentItem };
export interface TeEnList { [pk_entity: number]: InfTemporalEntity };
// export interface PropertyList { [pk_entity: number]: DfhProperty };
export class PropertyList { [pk_entity: string]: DfhProperty; }

export interface Panel {
    id: number;
    tabs: Tab[];
}

export type ListType = '' | 'entities' | 'sources' | 'queries' | 'visuals' | 'stories';

export interface Tab {
    // wheter tab is active or not
    active: boolean;
    // the root component included in this tab, in dash separate minuscles: EntityDetailComponent -> 'entity-detail'
    component: 'entity-detail' | 'source-detail' | 'section-detail' | 'query-detail';
    // icon to be displayed in tab, e.g.: gv-icon-source
    icon: 'persistent-entity' | 'temporal-entity' | 'source' | 'section' | 'query' | 'visual' | 'story';
    // name of the pathSegment under 'activeProject', used to generate the path: ['activeProject', pathSegment, uiId]
    pathSegment: 'entityDetails' | 'sourceDetails' | 'sectionDetails' | 'queryDetails';
    // data to pass to component via input variabales
    data?: {
        pkEntity?: number;
        classAndTypePk?: ClassAndTypePk;
    }
    // generated by reducer: base path where the component will be attatch his SubStore
    path?: string[];
    // generated on the fly, never in store
    tabTitle$?: Observable<string>;
    loading$?: Observable<boolean>;
}


export interface ProjectDetail extends ComProjectInterface {
    crm?: ProjectCrm,
    classSettings?: ClassSettingsI

    /******************************************************************
     * Data Cache
     */

    // data unit previews
    entityPreviews?: EntityPreviewList;

    // data unit details for display in modal
    peItModals?: PeItDetailList;

    // chunk List
    chunks?: ChunkList;

    // InfPersistentItems with roles by pk_entity
    peItGraphs?: PeItList;

    // InfPersistentItems with roles by pk_entity
    teEnGraphs?: TeEnList;


    /******************************************************************
     * Layout
     */
    list?: ListType;

    panels?: Panel[]

    // index of focused Panel
    focusedPanel?: number;

    // serial number for panels
    panelSerial?: number;

    // serial number for uiId
    uiIdSerial?: number;

    // reference the uiId within the path of the tab (uiId has nothing to do with pk_entity)
    entityDetails?: { [uiId: string]: EntityDetail }

    // reference the uiId within the path of the tab (uiId has nothing to do with pk_entity)
    sourceDetails?: { [uiId: string]: SourceDetail }

    // reference the uiId within the path of the tab (uiId has nothing to do with pk_entity)
    sectionDetails?: { [uiId: string]: SectionDetail }

    // reference the uiId within the path of the tab (uiId has nothing to do with pk_entity)
    queryDetails?: { [uiId: string]: QueryDetail }

    /******************************************************************
     * Things for Mentionings / Annotations
     */

    // the chunk that is used to create mentionings
    selectedChunk?: InfChunk;

    // if true, the text editor behaves so that each node can be clicked to de-/activate
    refiningChunk?: boolean;

    // true, when mentioning is being created.
    // TODO: check, if needed
    creatingMentioning?: boolean;

    // Array of pk_entities of mentionings (a.k.a. entity_associations of property "is mentioned in")
    // that are focused by a click on a chunk (in text editor)
    mentioningsFocusedInText?: number[]

    // Array of pk_entities of mentionings (a.k.a. entity_associations of property "is mentioned in")
    // that are focused by click on mentioning in a list/table view
    mentioningsFocusedInTable?: number[]

}

export interface ProjectCrm {
    classes?: ClassConfigList;
    properties?: PropertyList
    fieldList?: FieldList;
}

export interface ClassConfigList { [dfh_pk_class: number]: ClassConfig };

export interface ClassConfig {
    label: string;
    dfh_identifier_in_namespace: string;
    dfh_pk_class: number;
    subclassOf?: 'peIt' | 'teEnt'; // to distinguish TeEnts from PeIts
    isInProject?: boolean; // reflects the enabled / disabled state from data settings of the project
    propertyFields?: PropertyFieldList;
    uiContexts?: {
        [pk: number]: UiContext
    }
}

export interface UiContext extends ComUiContextInterface {
    uiElements?: UiElement[]
}

// short version of ComUiContextConfig
export interface UiElement {
    fk_property?: number,
    property_is_outgoing?: boolean,
    propertyFieldKey?: string, // TODO: merge the propertyFieldKey and propSetKey to fieldKey
    propSetKey?: string,
    fk_class_field?: number,
    class_field?: ComClassFieldInterface
    ord_num: number
}
