/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DatDigital { 
    pk_entity?: number;
    entity_version?: number;
    pk_text?: number;
    quill_doc?: object;
    string?: string;
    fk_system_type?: number;
    fk_namespace?: number;
}

