/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfStatement } from './infStatement';
import { WarEntityPreviewTimeSpan } from './warEntityPreviewTimeSpan';


export interface EntitySearchHit { 
    key?: string;
    pk_entity?: number;
    project_id: number;
    fk_class: number;
    class_label?: string;
    entity_label?: string;
    entity_type?: string;
    type_label?: string;
    fk_type?: number;
    time_span?: WarEntityPreviewTimeSpan;
    first_second?: string;
    last_second?: string;
    tmsp_last_modification?: string;
    full_text_headline?: string;
    class_label_headline?: string;
    entity_label_headline?: string;
    type_label_headline?: string;
    projects?: Array<number>;
    related_statements?: Array<InfStatement>;
}

