/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FactoidStatement } from './factoidStatement';


export interface FactoidEntity { 
    pkDigital?: number;
    pkClass?: number;
    pkRow?: number;
    pkColumn?: number;
    pkFactoidMapping?: number;
    headerStatements?: Array<FactoidStatement>;
    bodyStatements?: Array<FactoidStatement>;
}

