/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfStatementWithRelations } from './infStatementWithRelations';
import { QuillDoc } from './quillDoc';
import { InfLanguageWithRelations } from './infLanguageWithRelations';


/**
 * (tsType: InfLangStringWithRelations, schemaOptions: { includeRelations: true })
 */
export interface InfLangStringWithRelations { 
    pk_entity?: number;
    fk_class: number;
    quill_doc?: QuillDoc;
    string?: string;
    fk_language?: number;
    incoming_statements?: Array<InfStatementWithRelations>;
    language?: InfLanguageWithRelations;
}

