/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TabCell { 
    pk_cell?: number;
    fk_class?: number;
    fk_column?: number;
    fk_row?: number;
    fk_digital?: number;
    string_value?: string;
    numeric_value?: number;
}

