/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WarFieldChangeId { 
    fk_project: number;
    fk_source_info: number;
    fk_source_tables_cell: number;
    fk_property: number;
    is_outgoing: boolean;
}

