/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryDefinition } from './queryDefinition';
import { TimeChartContLine } from './timeChartContLine';


export interface AnalysisDefinition { 
    queryDefinition?: QueryDefinition;
    lines?: Array<TimeChartContLine>;
}

