/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ListType } from './listType';


<<<<<<< HEAD:client/src/app/core/sdk-lb4/model/importTableStateResponse.ts
export interface ImportTableStateResponse { 
    importing?: boolean;
=======
/**
 * System wide configuration for the class.
 */
export interface ClassConfig { 
    mapsToListType?: ListType;
>>>>>>> dev:client/src/app/core/sdk-lb4/model/classConfig.ts
}

