/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfStatementWithRelations } from './infStatementWithRelations';
import { DatNamespaceWithRelations } from './datNamespaceWithRelations';
import { DatDigitalWithRelations } from './datDigitalWithRelations';


/**
 * (tsType: DatChunkWithRelations, schemaOptions: { includeRelations: true })
 */
export interface DatChunkWithRelations { 
    pk_entity?: number;
    quill_doc?: object;
    string?: string;
    fk_entity_version: number;
    fk_text: number;
    fk_namespace: number;
    outgoing_statements?: Array<InfStatementWithRelations>;
    digital?: DatDigitalWithRelations;
    namespace?: DatNamespaceWithRelations;
}

