/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WarEntityPreview } from './warEntityPreview';
import { CzmlSpatialValue } from './czmlSpatialValue';
import { MapTemporalData } from './mapTemporalData';


export interface GeoEntityMapAndTimeCont { 
    geo_entity_pk: number;
    geo_entity_preview: WarEntityPreview;
    geo_positions: Array<CzmlSpatialValue>;
    pk_entities: Array<number>;
    temporal_data: MapTemporalData;
}

