/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProInfoProjRel } from './proInfoProjRel';
import { ProClassFieldConfig } from './proClassFieldConfig';
import { ProAnalysis } from './proAnalysis';


export interface ProObject { 
    info_proj_rel?: Array<ProInfoProjRel>;
    analysis?: Array<ProAnalysis>;
    class_field_config?: Array<ProClassFieldConfig>;
}

