/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SysAnalysisType { 
    standard_label?: string;
    rows_limit: number;
    pk_entity?: number;
    entity_version?: number;
    tmsp_creation?: string;
    tmsp_last_modification?: string;
}

