/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimePrimitiveWithCalWithRelations } from './timePrimitiveWithCalWithRelations';


/**
 * (tsType: TimeSpanWithRelations, schemaOptions: { includeRelations: true })
 */
export interface TimeSpanWithRelations { 
    _71?: TimePrimitiveWithCalWithRelations;
    _72?: TimePrimitiveWithCalWithRelations;
    _150?: TimePrimitiveWithCalWithRelations;
    _151?: TimePrimitiveWithCalWithRelations;
    _152?: TimePrimitiveWithCalWithRelations;
    _153?: TimePrimitiveWithCalWithRelations;
}

