/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimePrimitiveWithCalWithRelations } from './timePrimitiveWithCalWithRelations';


/**
 * (tsType: WarEntityPreviewTimeSpanWithRelations, schemaOptions: { includeRelations: true })
 */
export interface WarEntityPreviewTimeSpanWithRelations { 
    p82?: TimePrimitiveWithCalWithRelations;
    p81?: TimePrimitiveWithCalWithRelations;
    p81a?: TimePrimitiveWithCalWithRelations;
    p82a?: TimePrimitiveWithCalWithRelations;
    p81b?: TimePrimitiveWithCalWithRelations;
    p82b?: TimePrimitiveWithCalWithRelations;
}

