export const PK_DEFAULT_CONFIG_PROJECT = 375669;
export const PK_PROPERTY_HAS_TIME_SPAN = 4;
export const PK_PROPERTY_REFERS_TO = 1334;

export const PK_SYSTEM_TYPE__PRO_TEXT_PROPERTY__LABEL = 639;
export const PK_SYSTEM_TYPE__PRO_TEXT_PROPERTY__DESCRIPTION = 638;
