export const PK_DEFAULT_CONFIG_PROJECT = 375669;
export const PK_ENGLISH = 18889;
/**
 * OntoME Property IDs
 */
export const PK_PROPERTY_HAS_TIME_SPAN = 4;
export const PK_PROPERTY_REFERS_TO = 1334;

export const PROPERTY_PK_R42_IS_REP_MANIFESTATION_SINGLETON_FOR = 1016;
export const PROPERTY_PK_R4_CARRIERS_PROVIDED_BY = 979;
export const PROPERTY_PK_P5_HAS_CARRIER_PROVIDED_BY = 1316;
export const PROPERTY_PK_P4_IS_SERVER_RESPONSE_TO_REQUEST = 1305;
/**
 * OntoME Class IDs
 */
export const CLASS_PK_EXPRESSION = 218;
export const CLASS_PK_MANIFESTATION_PRODUCT_TYPE = 219;
export const CLASS_PK_MANIFESTATION_SINGLETON = 220;
export const CLASS_PK_ITEM = 221;
export const CLASS_PK_WEB_REQUEST = 502;


export const PK_SYSTEM_TYPE__PRO_TEXT_PROPERTY__LABEL = 639;
export const PK_SYSTEM_TYPE__PRO_TEXT_PROPERTY__DESCRIPTION = 638;
