/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiPropertyProfile { 
  [key: string]: object | any;


    propertyID: number;
    propertyLabelLanguage: string;
    propertyLabel: string;
    propertyInverseLabel: string;
    propertyScopeNoteLanguage: string;
    propertyScopeNote: string;
    isInherited: boolean;
    propertyDomain: number;
    domainInstancesMinQuantifier?: number;
    domainInstancesMaxQuantifier?: number;
    propertyRange: number;
    rangeInstancesMinQuantifier?: number;
    rangeInstancesMaxQuantifier?: number;
    identityDefining: boolean;
    isHasTypeSubproperty: boolean;
    propertyIdentifierInNamespace: string;
    namespaceURI?: string;
    namespaceID: number;
    namespaceLabelLanguage: string;
    namespaceLabel: string;
    profileAssociationType?: string;
    profileID: number;
    profileLabelLanguage: string;
    profileLabel: string;
}

