/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommunityVisibilityOptions } from './communityVisibilityOptions';
import { GvFieldTargetViewType } from './gvFieldTargetViewType';
import { AllowedCommunityVisibility } from './allowedCommunityVisibility';
import { ProjectVisibilityOptions } from './projectVisibilityOptions';
import { SysConfigFormCtrlType } from './sysConfigFormCtrlType';
import { SysConfigValueObjectType } from './sysConfigValueObjectType';


/**
 * System wide configuration for the class.
 */
export interface ClassConfig { 
    viewType?: GvFieldTargetViewType;
    formControlType?: SysConfigFormCtrlType;
    valueObjectType?: SysConfigValueObjectType;
    excludedFromEntities?: boolean;
    communityVisibilityRange?: AllowedCommunityVisibility;
    communityVisibilityDefault?: CommunityVisibilityOptions;
    projectVisibilityDefault?: ProjectVisibilityOptions;
}

