/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DatColumn { 
    fk_digital?: number;
    fk_data_type?: number;
    fk_column_content_type?: number;
    fk_column_relationship_type?: number;
    fk_original_column?: number;
    is_imported?: boolean;
    pk_entity?: number;
    fk_namespace?: number;
}

