/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DefaultFactoidPropertyMapping } from './defaultFactoidPropertyMapping';


export interface FactoidPropertyMapping { 
    pkEntity?: number;
    pkFactoidMapping?: number;
    pkProperty?: number;
    isOutgoing?: boolean;
    pkColumn?: number;
    comment?: string;
    _default?: DefaultFactoidPropertyMapping;
}

