/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GvFieldPageScope } from './gvFieldPageScope';
import { GvFieldSourceEntity } from './gvFieldSourceEntity';
import { GvFieldProperty } from './gvFieldProperty';


export interface GvFieldPage { 
    source: GvFieldSourceEntity;
    property: GvFieldProperty;
    isOutgoing: boolean;
    limit: number;
    offset: number;
    scope: GvFieldPageScope;
}

