/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfTimePrimitive } from './infTimePrimitive';
import { InfAppellation } from './infAppellation';
import { InfDimension } from './infDimension';
import { InfLangString } from './infLangString';
import { InfPlace } from './infPlace';
import { InfLanguage } from './infLanguage';


export interface InfData { 
    resource?: object;
    statement?: object;
    appellation?: InfAppellation;
    place?: InfPlace;
    dimension?: InfDimension;
    timePrimitive?: InfTimePrimitive;
    language?: InfLanguage;
    langString?: InfLangString;
}

