/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfResource } from './infResource';
import { InfTimePrimitive } from './infTimePrimitive';
import { InfAppellation } from './infAppellation';
import { InfStatement } from './infStatement';
import { InfDimension } from './infDimension';
import { InfLangString } from './infLangString';
import { InfPlace } from './infPlace';
import { InfLanguage } from './infLanguage';


export interface InfObject { 
    resource?: Array<InfResource>;
    statement?: Array<InfStatement>;
    place?: Array<InfPlace>;
    language?: Array<InfLanguage>;
    appellation?: Array<InfAppellation>;
    time_primitive?: Array<InfTimePrimitive>;
    lang_string?: Array<InfLangString>;
    dimension?: Array<InfDimension>;
}

