/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfResource } from './infResource';
import { InfTimePrimitive } from './infTimePrimitive';
import { ProInfoProjRel } from './proInfoProjRel';
import { InfAppellation } from './infAppellation';
import { InfStatement } from './infStatement';
import { DatDigital } from './datDigital';
import { InfDimension } from './infDimension';
import { DatChunk } from './datChunk';
import { InfLangString } from './infLangString';
import { InfPlace } from './infPlace';
import { InfLanguage } from './infLanguage';


export interface InfStatementWithRelations { 
    pk_entity?: number;
    fk_subject_info?: number;
    fk_subject_data?: number;
    fk_subject_tables_cell?: number;
    fk_subject_tables_row?: string;
    fk_property?: number;
    fk_property_of_property?: number;
    fk_object_info?: number;
    fk_object_data?: number;
    fk_object_tables_cell?: number;
    fk_object_tables_row?: number;
    is_in_project_count?: number;
    is_standard_in_project_count?: number;
    community_favorite_calendar?: string;
    entity_version_project_rels?: Array<ProInfoProjRel>;
    subject_resource?: InfResource;
    subject_chunk?: DatChunk;
    subject_statement?: InfStatement;
    subject_digital?: DatDigital;
    object_resource?: InfResource;
    object_appellation?: InfAppellation;
    object_time_primitive?: InfTimePrimitive;
    object_language?: InfLanguage;
    object_lang_string?: InfLangString;
    object_dimension?: InfDimension;
    object_place?: InfPlace;
    object_chunk?: DatChunk;
}

