/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InfStatement } from './infStatement';


export interface InfTemporalEntityWithRelations { 
    pk_entity?: number;
    fk_class: number;
    outgoing_statements?: Array<InfStatement>;
    incoming_statements?: Array<InfStatement>;
}

