/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectVisibilityOptions } from './projectVisibilityOptions';


/**
 * (tsType: ProInfoProjRelWithRelations, schemaOptions: { includeRelations: true })
 */
export interface ProInfoProjRelWithRelations { 
    pk_entity?: number;
    fk_project?: number;
    fk_entity?: number;
    fk_entity_version?: string;
    fk_entity_version_concat?: string;
    is_in_project?: boolean;
    is_standard_in_project?: boolean;
    ord_num_of_domain?: number;
    ord_num_of_range?: number;
    fk_creator?: number;
    fk_last_modifier?: number;
    project_visibility?: ProjectVisibilityOptions;
}

