/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: QuillOperationWithRelations, schemaOptions: { includeRelations: true })
 */
export interface QuillOperationWithRelations { 
    insert?: string;
    _delete?: number;
    retain?: number;
    /**
     * (tsType: AttributeMapWithRelations, schemaOptions: { includeRelations: true })
     */
    attributes?: { [key: string]: object; };
}

