/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SysConfigFieldsOfSourceSuperClass } from './sysConfigFieldsOfSourceSuperClass';
import { SysConfigFieldsOfSourceClass } from './sysConfigFieldsOfSourceClass';
import { SysConfigFieldDisplay } from './sysConfigFieldDisplay';


export interface SysConfigSpecialFields { 
    incomingProperties?: { [key: string]: SysConfigFieldDisplay; };
    outgoingProperties?: { [key: string]: SysConfigFieldDisplay; };
    bySourceClass?: { [key: string]: SysConfigFieldsOfSourceClass; };
    bySourceSuperClass?: Array<SysConfigFieldsOfSourceSuperClass>;
    hasTypeSubproperties?: SysConfigFieldDisplay;
}

