/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SysConfigOptionalProfiles } from './sysConfigOptionalProfiles';


export interface SysConfigOntomeProfiles { 
    requiredOntomeProfiles: Array<number>;
    optionalOntomeProfiles?: Array<SysConfigOptionalProfiles>;
}

