/**
 * geovistory
 * Geovistory – Platform for Digital History
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Section } from './section';


export interface SysConfigFieldDisplay { 
    comment?: string;
    formSections?: { [key: string]: Section; };
    viewSections?: { [key: string]: Section; };
    isHasTimeSpanShortCut?: boolean;
}

