# This is a basic workflow to help you get started with Actions

name: deploy-dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the dev branch
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  push-to-deploy-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Step1
      - name: Switch branch
        run: git checkout dev-deploy

      # Step2
      - name: Pull the new code
        run: git pull origin dev
        
      # Step3
      - name: Build front-end
        run: |
          cd client
          npm run build:all
          cd ..
          
      # Step4
      - name: Manual push dist folder
        run: |
          git add --force ./client/dist/*
          git commit -m "dist folder"
          git push origin dev-deploy
